-- =============================================================================
-- Alerts schema (PostgreSQL) — the "real system" design behind the demo API.
--
-- The running API keeps alerts in an in-memory ConcurrentDictionary; this file
-- documents how the same data and the status-update operation would be modeled
-- in Postgres with durability, optimistic concurrency, and an audit trail.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- alerts: one row per security alert.
--
-- CHECK constraints mirror the vocabulary shared with the frontend
-- (web/src/lib/types.ts) so invalid values are rejected at the database
-- boundary, not just in application code.
-- ---------------------------------------------------------------------------
CREATE TABLE alerts (
    -- Human-readable identifier, e.g. 'AL-0001'. Text PK keeps URLs and logs
    -- readable; a surrogate bigint/uuid would also be reasonable.
    id          text        PRIMARY KEY,

    title       text        NOT NULL,

    severity    text        NOT NULL
        CHECK (severity IN ('critical', 'high', 'medium', 'low')),

    status      text        NOT NULL
        CHECK (status IN ('open', 'acknowledged', 'resolved', 'false_positive')),

    source      text        NOT NULL
        CHECK (source IN (
            'CrowdStrike EDR',
            'Okta',
            'AWS GuardDuty',
            'Suricata IDS',
            'Email Gateway'
        )),

    -- When the alert was generated by the source system (timezone-aware).
    created_at  timestamptz NOT NULL,

    -- Analyst currently assigned; NULL means unassigned.
    assignee    text        NULL,

    -- Bumped on every mutation; useful for cache invalidation and debugging.
    updated_at  timestamptz NOT NULL DEFAULT now(),

    -- Optimistic-concurrency token. Clients read it (and may receive it as an
    -- ETag) and must send it back with writes; see the UPDATE pattern below.
    row_version integer     NOT NULL DEFAULT 1
);

-- The triage queue is the hot path: "open criticals, newest first" and
-- similar filters. A composite index on (status, severity, created_at DESC)
-- serves filter-by-status[/severity] with a recency sort without a re-sort.
CREATE INDEX idx_alerts_status_severity_created_at
    ON alerts (status, severity, created_at DESC);

-- ---------------------------------------------------------------------------
-- alert_status_history: append-only audit trail of every status transition.
--
-- Rows are never updated or deleted; this is the answer to "who changed this
-- alert, when, and from what to what" — required for SOC compliance reviews.
-- ---------------------------------------------------------------------------
CREATE TABLE alert_status_history (
    id          bigserial   PRIMARY KEY,
    alert_id    text        NOT NULL REFERENCES alerts (id),
    old_status  text        NOT NULL,
    new_status  text        NOT NULL,
    -- The authenticated principal that made the change (user id / service id).
    changed_by  text        NOT NULL,
    changed_at  timestamptz NOT NULL DEFAULT now()
);

-- Fast lookup of an alert's full history.
CREATE INDEX idx_alert_status_history_alert_id
    ON alert_status_history (alert_id, changed_at DESC);

-- ---------------------------------------------------------------------------
-- The transactional status update (what PATCH /api/alerts/{id}/status becomes).
--
-- Run inside a single transaction. Parameters:
--   $1 = alert id, $2 = new status, $3 = row_version the client last saw,
--   $4 = acting principal.
--
-- Step 1: conditional update guarded by row_version.
--
--   UPDATE alerts
--      SET status      = $2,
--          updated_at  = now(),
--          row_version = row_version + 1
--    WHERE id = $1
--      AND row_version = $3
--   RETURNING *;
--
--   * 1 row returned  -> success; the RETURNING row is the response body and
--                        its old status feeds the audit insert below.
--   * 0 rows returned -> either the id does not exist (-> 404) or another
--                        writer bumped row_version first (-> 409 Conflict;
--                        the client must re-fetch and retry). Distinguish the
--                        two with a follow-up SELECT ... WHERE id = $1.
--
-- Step 2: append to the audit trail in the same transaction so the history
-- can never drift from the alerts table.
--
--   INSERT INTO alert_status_history (alert_id, old_status, new_status, changed_by)
--   VALUES ($1, <status from before the update>, $2, $4);
--
-- COMMIT. If either statement fails, the whole transaction rolls back.
-- ---------------------------------------------------------------------------
